### ISSUE TITLE
Batches

### ISSUE THREAD

**Issue by QO-O** [madhusudan-kulkarni/youtube-watch-later-cleaner#1]
Hey! I'm not sure if I'm doing anything wrong (or how this site works.. So I think this is a way to report issues? If not, so so sorry!) since I'm a noob software dev student, but when I run this it deletes about 20 videos per batch and then just gives errors. From what I understood it would run in batches, with 5 minute breaks to avoid any issues. But it doesn't do any breaks, and just tries to keep deleting videos when YouTube is not responding anymore. Not sure if this is how it works or if the script broke, but figured it was worth reporting

**Comment by madhusudan-kulkarni** [comment]
Thanks for trying my extension! I’m aware of the issue. A revamped version with more features is coming next week, and this is already fixed in that. Stay tuned! 😊
